apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-appliance.fullname" . }}
  labels:
    {{- include "storage-appliance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.s3Port }}
    targetPort: s3
    protocol: TCP
    name: s3
  - port: {{ .Values.service.nvmeofPort }}
    targetPort: nvmeof
    protocol: TCP
    name: nvmeof
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "storage-appliance.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-appliance.fullname" . }}-headless
  labels:
    {{- include "storage-appliance.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.s3Port }}
    targetPort: s3
    protocol: TCP
    name: s3
  - port: {{ .Values.service.nvmeofPort }}
    targetPort: nvmeof
    protocol: TCP
    name: nvmeof
  selector:
    {{- include "storage-appliance.selectorLabels" . | nindent 4 }}
